### ISSUE TITLE
filename attribute can't get absolute path

### ISSUE THREAD

**Issue by idangozlan** [FormidableLabs/webpack-stats-plugin#34]
filename attribute can't get absolute path, it's always using publicPath as base location

**Comment by ryan-roemer** [comment]
Yep. The documentation for the `filename` fields notes the restriction in our docs here: https://github.com/FormidableLabs/webpack-stats-plugin#statswriterpluginopts

The reason is that the plugin emits compilation assets (See: https://github.com/FormidableLabs/webpack-stats-plugin/blob/master/lib/stats-writer-plugin.js#L101-L109)

If you have a first-class-webpack-plugin approach for supporting absolute urls, we'd love to see it!

**Comment by ryan-roemer** [comment]
Closing as old issue with known behavior. Feel free to re-open if there's some aspect this plugin _should_ be doing.
