### ISSUE TITLE
Output is missing "time" property

### ISSUE THREAD

**Issue by shwarcu** [FormidableLabs/webpack-stats-plugin#88]
Hi, 
I try to use this plugin to retrieve stats on how much does compilation take in webpack.
When I run webpack with options `--profile --json > compilation-stats.json` then I get `time` property in the output.
<img width="1257" alt="Screenshot 2022-07-22 at 15 26 16" src="https://user-images.githubusercontent.com/58426925/180449458-b3fcf78b-3c9d-4648-9f88-d981150f3791.png">

But when I use this plugin, `time` is missing even when I use `verbose` stats mode. 
Is this property intentionally stripped from the output? 

`time` can be also seen in the documentation of webpack https://v4.webpack.js.org/api/stats/

**Comment by ryan-roemer** [comment]
So, the issue is that the stats output file is part of the webpack compilation, and webpack doesn't assign the field until the compilation is complete after the hook we use (and we deliberately picked the latest hook we could to still emit during the compilation). See: https://github.com/FormidableLabs/webpack-stats-plugin/blob/main/lib/stats-writer-plugin.js#L80-L86

Here's an admittedly second class solution to just add in rough timings from start of webpack config read until getting to the stats writing which should be almost the last thing before complication is frozen:

```js
const START_TIME = Date.now()

module.exports = {
  // ...
  plugins: [
    new StatsWriterPlugin({
      transform(data) {
        return JSON.stringify(Object.assign(data, {
          time: Date.now() - START_TIME
        }), null, 2);
      }
    })
  ]
};
```

**Comment by shwarcu** [comment]
Thanks for explaining. I will give it a try as for now I don't see other option to measure webpack processing time programmatically without wrapping it with some script. My goal is to have a json file as an output with stats
